version: "3.5"

services:
  dicerunner-database:
    image: mongo:latest
    container_name: dicerunner-database
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - internal_network
    volumes:
      - ./internal/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: poggers

networks:
  internal_network:
    name: internal_network

volumes:
  mongo_data:
    driver: local